cern-eam/eam-light-frontend

src/ui/pages/Entity.js
=> [EAM-105] Hyperlink problem after WO creation

package.json, src/ui/pages/equipment/asset/AssetDetails.js
=> [EAM-74]Add hyperlink from Part field on Asset screen to Part screen in EAM Light

src/ui/pages/meter/MeterReadingContent.js, src/ui/pages/meter/MeterReadingSearch.js
Added barcode scanning to meter readings
=> [EAM-250] Meter readings: Add barcode scanning

package.json, src/ui/pages/Entity.js, src/ui/pages/EntityTools.js, src/ui/pages/work/Workorder.js, src/ui/pages/work/WorkorderGeneral.js
Also solves EAM-237.
Related backend PR: https://github.com/cern-eam/eam-light-backend/pull/20.
=> [EAM-364] Enhanced standard work order support

src/ui/pages/equipment/asset/Asset.js, src/ui/pages/equipment/position/Position.js, src/ui/pages/work/Workorder.js
Related PR: https://github.com/cern-eam/eam-components/pull/32
=> [EAM-426] Passed correct functions through react-redux to components

src/ui/pages/Entity.js, src/ui/pages/equipment/asset/Asset.js, src/ui/pages/equipment/asset/AssetDetails.js, src/ui/pages/equipment/position/Position.js, src/ui/pages/equipment/position/PositionDetails.js, src/ui/pages/equipment/system/System.js, src/ui/pages/equipment/system/SystemDetails.js, src/ui/pages/work/Workorder.js, src/ui/pages/work/WorkorderGeneral.js
Depends on https://github.com/cern-eam/eam-components/pull/40
=> [EAM-581] Moved input handlers from onChangeValue to componentDidUpdate

src/ui/components/userdefinedfields/UDFChar.js, src/ui/pages/equipment/asset/AssetDetails.js, src/ui/pages/equipment/components/EquipmentToolbar.js, src/ui/pages/equipment/location/components/LocationToolbar.js, src/ui/pages/part/PartToolbar.js, src/ui/pages/work/WorkorderGeneral.js, src/ui/pages/work/WorkorderToolbar.js
Changed the icon for the Infor EAM link.
=> [EAM-549] Distinguish between internal and external links

src/enums/EntityCode.js, src/ui/pages/search/SearchLinkUtils.js, src/ui/pages/search/SearchResult.js
Adds support for global search returning location links to the frontend.
=> [EAM-414] Locations on Global Search

src/reducers/applicationReducers.js, src/ui/components/EamlightToolbar.css, src/ui/components/EamlightToolbar.js, src/ui/components/EamlightToolbarContainer.js, src/ui/pages/equipment/asset/Asset.js, src/ui/pages/equipment/location/Location.js, src/ui/pages/equipment/position/Position.js, src/ui/pages/equipment/system/System.js, src/ui/pages/part/Part.js, src/ui/pages/work/Workorder.js
Displays the screen name on the entity toolbar for local administrators only
=> [EAM-584] Show screen name on entities

package.json, src/Eamlight.js, src/EamlightContainer.js, src/config.js, src/ui/layout/ApplicationLayout.css, src/ui/layout/ApplicationLayout.js, src/ui/layout/ApplicationLayoutContainer.js
**Depends on https://github.com/cern-eam/eam-components/pull/48 , make sure to release new version of eam-components and update package.json here before merging this**
=> [EAM-201] Added theming to EAM Light

src/ui/pages/work/partusage/PartUsageDialog.js
Functionality tested:
* Issue/Return part tracked by asset
* Issue/Return part tracked by quantity
=> [EAM-949] Fix add part usage - entering asset does not fill part nor bin

src/ui/pages/work/partusage/PartUsageDialog.js
**Depends on https://github.com/cern-eam/eam-components/pull/68**
=> [EAM-591] Improve bin selection in EAM Light add part usage

src/tools/WSEquipment.js, src/ui/pages/equipment/EquipmentRedirect.js
Needs:
https://github.com/cern-eam/eam-light-backend/pull/48
https://github.com/cern-eam/eam-wshub-core/pull/53
=> [EAM-862] Fetch only equipment type for redirect

src/ui/pages/work/activities/Activity.css, src/ui/pages/work/activities/Activity.js
This pr will simplify the spacing inside Activity component and fix an issue within a specific breakpoint, where text overlaps.
I also removed some unnecessary styling in favour of using spacing from material ui library.
=> [EAM-792] Simplify spacing for the activity component

src/ui/pages/work/activities/Activity.js
This pull request adds the total worked hours to the activity view.
The total worked hours is calculated from the booked labour, hours worked value.
=> [EAM-235] Add total hours worked to the activity view

src/ui/pages/equipment/position/PositionHierarchy.js
This pull request will change the "parent position" to "parent asset" in position hierarchy component
=> [EAM-1127] Fix parent asset issue

src/ui/pages/equipment/asset/AssetHierarchy.js, src/ui/pages/equipment/position/PositionHierarchy.js
This pull request will render inputs and dependent values only if the field is not hidden
=> [EAM-1128] Fix hierarchy field visibility issue

src/tools/WSEquipment.js, src/ui/pages/equipment/asset/AssetDetails.js, src/ui/pages/equipment/position/PositionDetails.js, src/ui/pages/equipment/system/SystemDetails.js
**Depends on https://github.com/cern-eam/eam-light-backend/pull/53**
=> [EAM-1196] Make categories for objects dependent on their class

src/tools/WSWorkorders.js, src/ui/pages/work/Workorder.js, src/ui/pages/work/WorkorderClosingCodes.js
**Please merge at the same time as https://github.com/cern-eam/eam-light-backend/pull/54**
=> [EAM-1257] Make closing codes take into account the same params as Infor

src/ui/components/EamlightToolbar.js, src/ui/components/Toolbar.js, src/ui/components/userdefinedfields/UserDefinedFields.js, src/ui/pages/Entity.js, src/ui/pages/equipment/asset/Asset.js, src/ui/pages/equipment/location/Location.js, src/ui/pages/equipment/location/LocationDetails.js, src/ui/pages/equipment/position/Position.js, src/ui/pages/equipment/system/System.js, src/ui/pages/equipment/system/SystemDetails.js, src/ui/pages/equipment/system/SystemGeneral.js, src/ui/pages/meter/MeterReadingContent.js, src/ui/pages/part/Part.js, src/ui/pages/work/Workorder.js, src/ui/pages/work/activities/Activities.js, src/ui/pages/work/meter/MeterReadingWO.js, src/ui/pages/work/partusage/PartUsage.js
**Before merging this PR, please merge https://github.com/cern-eam/eam-components/pull/78 + release and update package.json**
=> [EAM-1116] Respect read only mode based on departmental security

src/ui/components/customfields/inputs/CustomFieldCHAR.js, src/ui/components/customfields/inputs/CustomFieldDATE.js, src/ui/components/customfields/inputs/CustomFieldDATI.js
**Please merge + tag https://github.com/cern-eam/eam-components/pull/92 and update in package.json here before approving this PR**
=> [EAM-1284] Fix UOM for CHAR custom fields

package.json
**Make sure to release eam-components first, edit package.json here if required**
=> [EAM-1528] Enable tree shaking for EAM Light

src/ui/components/userdefinedfields/UserDefinedFields.js
**Please merge https://github.com/cern-eam/eam-light-backend/pull/59 first**
=> [EAM-219] Support UoM in UDF fields

package.json, src/tools/WS.js, src/tools/WSWatchers.js, src/tools/WSWorkorders.js, src/ui/components/EamlightToolbar.js, src/ui/components/EamlightToolbarContainer.js, src/ui/components/Toolbar.js, src/ui/components/watchlist/EditWatchlistDialog.js, src/ui/components/watchlist/Watchlist.js
Relies on https://github.com/cern-eam/eam-light-backend/pull/69
=> [EAM-1882] Watchlists for WOs

src/tools/WS.js
requires https://github.com/cern-eam/eam-light-backend/pull/67
=> [EAM-1299] Added new params to eqp autocomplete

src/ui/layout/menu/EamlightMenu.js, src/ui/layout/menu/MenuGridLink.js, src/ui/pages/equipment/asset/search/AssetSearch.js, src/ui/pages/equipment/location/search/LocationSearch.js, src/ui/pages/equipment/position/search/PositionSearch.js, src/ui/pages/equipment/system/search/SystemSearch.js, src/ui/pages/grid/Grid.js, src/ui/pages/part/search/PartSearch.js, src/ui/pages/work/search/WorkorderSearch.js
Requires https://github.com/cern-eam/eam-light-backend/pull/60
=> [EAM-1229] Custom grid support

src/ui/components/eqtree/EAMTree.js
Now expands every node with the same id instead of just the first.
=> [EAM-2299] Update expand node logic

package.json
Reference: https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined/70452191#70452191
=> Fix UI block after live reload for yarn

src/tools/WSWorkorders.js, src/ui/pages/work/activities/Activities.js, src/ui/pages/work/activities/Activity.js, src/ui/pages/work/activities/dialogs/AddActivityDialog.js
Requires:
- https://github.com/cern-eam/eam-light-backend/pull/97
- https://github.com/cern-eam/eam-wshub-core/pull/76
=> [EAM-1761][EAM-2317] add edit to WO activities/set default activity dialog values in FE

src/ui/pages/work/Workorder.js
Is related to:
- https://github.com/cern-eam/eam-components/pull/129
=> [EAM-1773] Pass prop to checklists to disable create follow-up WO according to layout

src/Eamlight.js, src/ui/layout/ApplicationLayout.js, src/ui/layout/Footer.js
Depends on:
- https://github.com/cern-eam/eam-components/pull/149
=> [EAM-2777] Replace EAM-Light Footer with EAM-Components Footer

src/ui/pages/work/activities/dialogs/AddBookLabourDialog.js
Depends on:
- https://github.com/cern-eam/eam-wshub-core/pull/87
=> [EAM-2156] Configuration EAM light pour saisie des heures

src/Eamlight.js, src/actions/applicationActions.js
Should avoid FE loading for ever on sporadic screen layout fetching errors.
=> [EAM-2811] Add error handling to screen layout fetching

src/tools/WS.js, src/ui/pages/work/WorkorderScheduling.js
Added new field 'Assigned by' in the scheduling of the work order. A new WS method has been created for the autocompletion of the supervisors.
=> [EAM-2960] Add field 'Assigned by' in EAMlight

src/tools/WSWorkorders.js, src/ui/pages/work/partusage/PartUsage.js, src/ui/pages/work/partusage/PartUsageContainer.js, src/ui/pages/work/partusage/PartUsageDialog.js
Depends on:
- https://github.com/cern-eam/eam-light-backend/pull/102
=> [EAM-2225] Add lot field and improvements to part usage dialog

src/tools/WSEquipment.js, src/ui/pages/equipment/replaceeqp/ReplaceEqp.js, src/ui/pages/equipment/replaceeqp/ReplaceEqpGeneral.js
Depends on:
- https://github.com/cern-eam/eam-light-backend/pull/105
=> EAM-2704 Show potentially detachable equipment

src/ui/pages/work/activities/Activity.js
=> [EAM-2965] Activity description change

src/state/useEquipmentTreeStore.js, src/ui/pages/equipment/Equipment.jsx, src/ui/pages/equipment/location/Location.jsx, src/ui/pages/equipment/position/Position.jsx, src/ui/pages/equipment/system/System.jsx
Not clear why we were doing this if condition:
```
if (!showEqpTree) {
updateEquipmentTreeData({equipment})
}
```
=> [EAM-3866] save isEqpTree open in the localStorage

src/ui/pages/EntityTools.jsx, src/ui/pages/equipment/EquipmentTools.js, src/ui/pages/equipment/asset/Asset.jsx, src/ui/pages/equipment/location/Location.jsx, src/ui/pages/equipment/position/Position.jsx, src/ui/pages/equipment/system/System.jsx
Depends on [PR](https://github.com/cern-eam/eam-wshub-core/pull/103)
=> [EAM-3969] Display custom HTML tabs for equipment entities
